services:
  - type: web
    name: eld-trip-planner
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: eld-trip-planner-db
          property: connectionString

databases:
  - name: eld-trip-planner-db
    databaseName: eld_trip_planner
    user: eld_user
